In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import os

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
PATH =  '/content/drive/MyDrive'

In [6]:
output_prob_1 = pd.read_csv(os.path.join(PATH, 'output_prob_df_electra.csv'), encoding='utf-8')
output_prob_2 = pd.read_csv(os.path.join(PATH, 'output_prob_df_robert.csv'), encoding='utf-8')

In [11]:
electra_list = output_prob_1.values
print(electra_list)

[[0.00365691 0.99189621 0.00444687]
 [0.15394023 0.03173437 0.81432539]
 [0.15941782 0.03396682 0.80661529]
 ...
 [0.00648467 0.00340608 0.99010921]
 [0.00232586 0.00385985 0.99381435]
 [0.08876292 0.73923564 0.17200147]]


In [12]:
robert_list = output_prob_2.values
print(robert_list)

[[7.58384878e-04 9.98633683e-01 6.07933674e-04]
 [4.62397784e-01 1.67547856e-02 5.20847440e-01]
 [7.45141506e-01 5.91057120e-03 2.48947859e-01]
 ...
 [4.30150749e-03 1.05626415e-03 9.94642258e-01]
 [2.94729043e-03 6.70121750e-04 9.96382594e-01]
 [8.21434736e-01 3.62621099e-02 1.42303199e-01]]


In [13]:
# 각각의 가중치 0.4, 0.6
koelectra_probs_w1 = 0.4
klue_roberta_probs_w2 = 0.6

average_probs = [koelectra_probs_w1 * p1 + klue_roberta_probs_w2 * p2 for p1, p2 in zip(electra_list, robert_list)]

print(average_probs)

[array([0.00191779, 0.99593869, 0.00214351]), array([0.33901476, 0.02274662, 0.63823862]), array([0.51085203, 0.01713307, 0.47201483]), array([0.00223084, 0.98507378, 0.01269535]), array([0.04159706, 0.94549478, 0.01290817]), array([0.00214236, 0.05965273, 0.93820491]), array([0.01191409, 0.00606231, 0.98202363]), array([0.68999296, 0.22632598, 0.08368105]), array([0.95642489, 0.00228813, 0.04128705]), array([0.30848159, 0.16021817, 0.53130025]), array([0.00210032, 0.99285944, 0.00504025]), array([0.99455941, 0.00222463, 0.00321605]), array([0.0011555 , 0.9956409 , 0.00320361]), array([0.97083288, 0.02267988, 0.00648722]), array([0.00389271, 0.01677732, 0.97932996]), array([0.00356199, 0.00159182, 0.99484622]), array([0.65790945, 0.01618185, 0.32590867]), array([0.00174334, 0.0026616 , 0.99559509]), array([0.00252875, 0.92855818, 0.06891304]), array([0.00317902, 0.00138079, 0.99544023]), array([0.0013797, 0.9802032, 0.0184171]), array([0.03665989, 0.30662386, 0.65671623]), array([0.301

In [14]:
pred_answer = []
for prob in average_probs:
  pred_answer.append(np.argmax(prob, axis = -1))

print(pred_answer)

[1, 2, 0, 1, 1, 2, 2, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 2, 1, 2, 1, 2, 2, 0, 1, 1, 0, 0, 0, 2, 1, 1, 1, 2, 2, 1, 0, 1, 0, 1, 2, 0, 2, 2, 2, 1, 2, 0, 1, 0, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 2, 2, 1, 0, 2, 0, 0, 2, 2, 0, 2, 2, 1, 2, 1, 1, 1, 0, 0, 2, 1, 0, 2, 1, 2, 0, 1, 0, 2, 1, 2, 0, 2, 2, 0, 2, 0, 2, 0, 2, 2, 1, 0, 1, 2, 1, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 0, 0, 0, 1, 2, 1, 2, 1, 0, 2, 0, 1, 2, 1, 1, 2, 2, 2, 0, 2, 1, 0, 1, 2, 2, 1, 0, 1, 2, 0, 0, 0, 1, 2, 2, 0, 0, 2, 0, 2, 1, 2, 0, 2, 0, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 0, 2, 2, 2, 0, 2, 1, 2, 0, 1, 2, 2, 1, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 2, 0, 1, 1, 2, 2, 0, 1, 2, 1, 1, 2, 1, 1, 0, 2, 0, 0, 0, 2, 2, 1, 0, 0, 0, 1, 2, 2, 2, 0, 2, 2, 1, 1, 0, 2, 2, 0, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 2, 2, 1, 0, 2, 0, 2, 2, 0, 0, 2, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 0, 2, 1, 0, 2, 0, 1, 0, 2, 0, 1, 1, 1, 2, 0, 2, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 1, 2, 1, 0, 1, 1, 2, 0, 0, 

In [15]:
def num_to_label(label):
    label_dict = {0: "entailment", 1: "contradiction", 2: "neutral"}
    str_label = []

    for i, v in enumerate(label):
        str_label.append([i,label_dict[v]])

    return str_label

answer = num_to_label(pred_answer)
print(answer)

[[0, 'contradiction'], [1, 'neutral'], [2, 'entailment'], [3, 'contradiction'], [4, 'contradiction'], [5, 'neutral'], [6, 'neutral'], [7, 'entailment'], [8, 'entailment'], [9, 'neutral'], [10, 'contradiction'], [11, 'entailment'], [12, 'contradiction'], [13, 'entailment'], [14, 'neutral'], [15, 'neutral'], [16, 'entailment'], [17, 'neutral'], [18, 'contradiction'], [19, 'neutral'], [20, 'contradiction'], [21, 'neutral'], [22, 'neutral'], [23, 'entailment'], [24, 'contradiction'], [25, 'contradiction'], [26, 'entailment'], [27, 'entailment'], [28, 'entailment'], [29, 'neutral'], [30, 'contradiction'], [31, 'contradiction'], [32, 'contradiction'], [33, 'neutral'], [34, 'neutral'], [35, 'contradiction'], [36, 'entailment'], [37, 'contradiction'], [38, 'entailment'], [39, 'contradiction'], [40, 'neutral'], [41, 'entailment'], [42, 'neutral'], [43, 'neutral'], [44, 'neutral'], [45, 'contradiction'], [46, 'neutral'], [47, 'entailment'], [48, 'contradiction'], [49, 'entailment'], [50, 'neutra

In [16]:
df = pd.DataFrame(answer, columns=['index', 'label'])

print(df)

      index          label
0         0  contradiction
1         1        neutral
2         2     entailment
3         3  contradiction
4         4  contradiction
...     ...            ...
1661   1661        neutral
1662   1662        neutral
1663   1663        neutral
1664   1664        neutral
1665   1665     entailment

[1666 rows x 2 columns]


In [ ]:
df.to_csv('./result/submission_ensemble.csv', index=False)